---
driver_plugin: vagrant
driver_config:
  # require_chef_omnibus: latest # will install on each run
  require_chef_omnibus: 11.6.0

platforms:

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - "recipe[apt]"

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box
  run_list:
  - "recipe[apt]"

- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - "recipe[apt]"

- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
  run_list:
  - "recipe[yum]"

- name: centos-5.10
  driver_config:
    box: opscode-centos-5.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10_chef-provisionerless.box
  run_list:
  - "recipe[yum]"

# not going to try until
# https://jira.mongodb.org/browse/SERVER-7285 is closed
#- name: fedora-19
  #driver_config:
    #box: opscode-fedora-19
    #box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
  #run_list:
  #- "recipe[yum]"

 #- name: fedora-20
  #driver_config:
    #box: opscode-fedora-20
    #box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-20_chef-provisionerless.box
  #run_list:
  #- "recipe[yum]"

# maybe again oneday
 #- name: freebsd-9.2
  #driver_config:
    #box: opscode-freebsd-9.2
    #box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-9.2_chef-provisionerless.box
  #run_list:
  #- "recipe[yum]"

suites:
- name: default
  run_list:
  - "recipe[mongodb]"
  attributes: {}

- name: default_10gen
  run_list:
  - "recipe[mongodb::10gen_repo]"
  - "recipe[mongodb]"
  attributes: {}

- name: configserver
  run_list:
  - "recipe[mongodb::configserver]"
  attributes: {}

- name: mongos
  run_list:
  - "recipe[chef-solo-search]"
  - "recipe[mongodb::mongos]"
  attributes:
    mongodb:
      cluster_name: default

- name: mms_agent
  run_list:
  - "recipe[mongodb::mms-agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
